# intro task
git fetch AhimasYD
git fetch rakhele
git fetch sinelnikovmaxim
git fetch Pavel-by
git fetch pajecawav
git fetch otsheln1k
git fetch scissorsnatcher
git fetch AlexRyzhickov
git fetch smotritetamptiza
git fetch a-kuzina
